draw_set_halign(fa_left);
draw_set_valign(fa_middle);
draw_set_colour($e4924f);
draw_set_font(fnt_debug);
draw_text(x - 15, y-15, string(dpad_dir));
draw_text(x - 15, y-25, string(state));
draw_text(x - 15, y-35, "j " + string(jump[0]) + string(jump[1]) + string(jump[2]));
draw_text(x - 15, y-45, "d " + string(dodge[0]) + string(dodge[1]) + string(dodge[2]));
draw_text(x - 15, y-55, "x " + string(velocity[XAXIS]));
draw_text(x - 15, y-65, "y " + string(velocity[YAXIS]));